"""add fuel receipt source fields

Revision ID: 18560ac15f58
Revises: c78fe5a168bc
Create Date: 2026-09-05 11:44:43.103789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18560ac15f58'
down_revision: Union[str, Sequence[str], None] = 'c78fe5a168bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_transactions', sa.Column('source_vessel_id', sa.Integer(), nullable=True))
    op.add_column('fuel_transactions', sa.Column('fuel_source', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_fuel_transactions_source_vessel_id'), 'fuel_transactions', ['source_vessel_id'], unique=False)
    op.create_foreign_key(None, 'fuel_transactions', 'vessels', ['source_vessel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fuel_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_fuel_transactions_source_vessel_id'), table_name='fuel_transactions')
    op.drop_column('fuel_transactions', 'fuel_source')
    op.drop_column('fuel_transactions', 'source_vessel_id')
    # ### end Alembic commands ###
