"""enforce unique vessel shift per day

Revision ID: 19011507a8f8
Revises: c597076887a9
Create Date: 2026-09-03 17:11:40.032240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19011507a8f8'
down_revision: Union[str, Sequence[str], None] = 'c597076887a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shifts_vessel_date_name', 'shifts', ['vessel_id', 'shift_date', 'shift_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shifts_vessel_date_name', 'shifts', type_='unique')
    # ### end Alembic commands ###
