"""add vessel fuel threshold

Revision ID: 5fc26f6f4304
Revises: 18560ac15f58
Create Date: 2026-09-05 12:33:49.888807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc26f6f4304'
down_revision: Union[str, Sequence[str], None] = '18560ac15f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessels', sa.Column('fuel_threshold_litres', sa.Numeric(precision=12, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vessels', 'fuel_threshold_litres')
    # ### end Alembic commands ###
