"""add shift to engine events

Revision ID: 83869f46c465
Revises: 58fce57c9f91
Create Date: 2026-09-04 10:42:29.752170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83869f46c465'
down_revision: Union[str, Sequence[str], None] = '58fce57c9f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'engine_events',
        sa.Column('shift_id', sa.Integer(), nullable=True)
    )

    op.create_index(
        op.f('ix_engine_events_shift_id'),
        'engine_events',
        ['shift_id'],
        unique=False
    )

    op.create_foreign_key(
        None,
        'engine_events',
        'shifts',
        ['shift_id'],
        ['id']
    )

    op.alter_column(
        'engine_events',
        'shift_id',
        existing_type=sa.Integer(),
        nullable=False
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'engine_events', type_='foreignkey')
    op.drop_index(op.f('ix_engine_events_shift_id'), table_name='engine_events')
    op.drop_column('engine_events', 'shift_id')
    # ### end Alembic commands ###
