"""add production records

Revision ID: 898db80ad781
Revises: ecc93dd5109b
Create Date: 2026-09-07 11:00:16.172326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898db80ad781'
down_revision: Union[str, Sequence[str], None] = 'ecc93dd5109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('as_per_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('true_qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('fuel_rate', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_records_created_by_user_id'), 'production_records', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_production_records_production_date'), 'production_records', ['production_date'], unique=False)
    op.create_index(op.f('ix_production_records_project_id'), 'production_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_production_records_shift_id'), 'production_records', ['shift_id'], unique=False)
    op.create_index(op.f('ix_production_records_vessel_id'), 'production_records', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_records_vessel_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_shift_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_project_id'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_production_date'), table_name='production_records')
    op.drop_index(op.f('ix_production_records_created_by_user_id'), table_name='production_records')
    op.drop_table('production_records')
    # ### end Alembic commands ###
