"""add shifts to fuel transfers

Revision ID: 8e9a732da498
Revises: 83869f46c465
Create Date: 2026-09-04 11:42:54.780009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9a732da498'
down_revision: Union[str, Sequence[str], None] = '83869f46c465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('from_shift_id', sa.Integer(), nullable=False))
    op.add_column('transfers', sa.Column('to_shift_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_transfers_from_shift_id'), 'transfers', ['from_shift_id'], unique=False)
    op.create_index(op.f('ix_transfers_to_shift_id'), 'transfers', ['to_shift_id'], unique=False)
    op.create_foreign_key(None, 'transfers', 'shifts', ['from_shift_id'], ['id'])
    op.create_foreign_key(None, 'transfers', 'shifts', ['to_shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_constraint(None, 'transfers', type_='foreignkey')
    op.drop_index(op.f('ix_transfers_to_shift_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_from_shift_id'), table_name='transfers')
    op.drop_column('transfers', 'to_shift_id')
    op.drop_column('transfers', 'from_shift_id')
    # ### end Alembic commands ###
