"""add user role constraint

Revision ID: a1f2b8f3e181
Revises: 19011507a8f8
Create Date: 2026-09-03 17:26:31.690996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f2b8f3e181'
down_revision: Union[str, Sequence[str], None] = '19011507a8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_users_role_valid', 'users', "role IN ('ADMIN', 'MANAGER', 'OPERATOR')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role_valid', 'users', type_='check')
    # ### end Alembic commands ###
