"""add adjustment direction to fuel transactions

Revision ID: c597076887a9
Revises: e718160aad9d
Create Date: 2026-09-03 17:06:11.933935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c597076887a9'
down_revision: Union[str, Sequence[str], None] = 'e718160aad9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_transactions', sa.Column('adjustment_direction', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_transactions', 'adjustment_direction')
    # ### end Alembic commands ###
