"""add vessel site and type

Revision ID: c839475d3f6c
Revises: d50f19e6286d
Create Date: 2026-09-10 15:07:25.523306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c839475d3f6c'
down_revision: Union[str, Sequence[str], None] = 'd50f19e6286d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessels', sa.Column('site_id', sa.Integer(), nullable=True))
    op.add_column('vessels', sa.Column('vessel_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_vessels_site_id'), 'vessels', ['site_id'], unique=False)
    op.create_foreign_key(None, 'vessels', 'sites', ['site_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vessels', type_='foreignkey')
    op.drop_index(op.f('ix_vessels_site_id'), table_name='vessels')
    op.drop_column('vessels', 'vessel_type')
    op.drop_column('vessels', 'site_id')
    # ### end Alembic commands ###
