"""add transfer attachments

Revision ID: d7e97511581a
Revises: f88381657121
Create Date: 2026-09-10 16:27:56.814791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e97511581a'
down_revision: Union[str, Sequence[str], None] = 'f88381657121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_attachments_attachment_id'), 'transfer_attachments', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_transfer_attachments_transfer_id'), 'transfer_attachments', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_attachments_transfer_id'), table_name='transfer_attachments')
    op.drop_index(op.f('ix_transfer_attachments_attachment_id'), table_name='transfer_attachments')
    op.drop_table('transfer_attachments')
    # ### end Alembic commands ###
