"""add soundings

Revision ID: d9727f43bd47
Revises: 5fc26f6f4304
Create Date: 2026-09-05 13:25:04.377279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9727f43bd47'
down_revision: Union[str, Sequence[str], None] = '5fc26f6f4304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soundings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('reading', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vessel_id', 'report_date', name='uq_sounding_vessel_report_date')
    )
    op.create_index(op.f('ix_soundings_report_date'), 'soundings', ['report_date'], unique=False)
    op.create_index(op.f('ix_soundings_submitted_by_user_id'), 'soundings', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_soundings_vessel_id'), 'soundings', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soundings_vessel_id'), table_name='soundings')
    op.drop_index(op.f('ix_soundings_submitted_by_user_id'), table_name='soundings')
    op.drop_index(op.f('ix_soundings_report_date'), table_name='soundings')
    op.drop_table('soundings')
    # ### end Alembic commands ###
