"""add shift attachments

Revision ID: e69cdbf9613f
Revises: 898db80ad781
Create Date: 2026-09-07 17:44:44.400142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69cdbf9613f'
down_revision: Union[str, Sequence[str], None] = '898db80ad781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_attachments_attachment_id'), 'shift_attachments', ['attachment_id'], unique=False)
    op.create_index(op.f('ix_shift_attachments_attachment_type'), 'shift_attachments', ['attachment_type'], unique=False)
    op.create_index(op.f('ix_shift_attachments_created_by_user_id'), 'shift_attachments', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shift_attachments_shift_id'), 'shift_attachments', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_attachments_shift_id'), table_name='shift_attachments')
    op.drop_index(op.f('ix_shift_attachments_created_by_user_id'), table_name='shift_attachments')
    op.drop_index(op.f('ix_shift_attachments_attachment_type'), table_name='shift_attachments')
    op.drop_index(op.f('ix_shift_attachments_attachment_id'), table_name='shift_attachments')
    op.drop_table('shift_attachments')
    # ### end Alembic commands ###
