"""add fuel ledger engine events and transfers

Revision ID: e718160aad9d
Revises: 82bae7ffed5f
Create Date: 2026-09-03 16:56:45.315700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e718160aad9d'
down_revision: Union[str, Sequence[str], None] = '82bae7ffed5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_vessel_id', sa.Integer(), nullable=False),
    sa.Column('to_vessel_id', sa.Integer(), nullable=False),
    sa.Column('initiated_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('loss_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_remark', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_vessel_id <> to_vessel_id', name='ck_transfers_different_vessels'),
    sa.CheckConstraint('initiated_quantity > 0', name='ck_transfers_initiated_quantity_positive'),
    sa.CheckConstraint('loss_quantity IS NULL OR loss_quantity >= 0', name='ck_transfers_loss_quantity_nonnegative'),
    sa.CheckConstraint('received_quantity IS NULL OR received_quantity >= 0', name='ck_transfers_received_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_vessel_id'], ['vessels.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_from_vessel_id'), 'transfers', ['from_vessel_id'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index(op.f('ix_transfers_to_vessel_id'), 'transfers', ['to_vessel_id'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_date'), 'transfers', ['transfer_date'], unique=False)
    op.create_table('engine_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stop_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hours_run', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('consumption', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('lph_rate', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engine_events_created_by_user_id'), 'engine_events', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_engine_events_equipment_id'), 'engine_events', ['equipment_id'], unique=False)
    op.create_table('fuel_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('vessel_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_fuel_transactions_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_transactions_created_by_user_id'), 'fuel_transactions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_shift_id'), 'fuel_transactions', ['shift_id'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_transaction_date'), 'fuel_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_transaction_type'), 'fuel_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_fuel_transactions_vessel_id'), 'fuel_transactions', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_transactions_vessel_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_transaction_type'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_transaction_date'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_shift_id'), table_name='fuel_transactions')
    op.drop_index(op.f('ix_fuel_transactions_created_by_user_id'), table_name='fuel_transactions')
    op.drop_table('fuel_transactions')
    op.drop_index(op.f('ix_engine_events_equipment_id'), table_name='engine_events')
    op.drop_index(op.f('ix_engine_events_created_by_user_id'), table_name='engine_events')
    op.drop_table('engine_events')
    op.drop_index(op.f('ix_transfers_transfer_date'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_to_vessel_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_from_vessel_id'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
