"""add attachments and update soundings

Revision ID: ecc93dd5109b
Revises: d9727f43bd47
Create Date: 2026-09-05 13:33:35.739853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc93dd5109b'
down_revision: Union[str, Sequence[str], None] = 'd9727f43bd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_attachments_uploaded_by_user_id'), 'attachments', ['uploaded_by_user_id'], unique=False)
    op.add_column('soundings', sa.Column('attachment_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_sounding_vessel_report_date'), 'soundings', type_='unique')
    op.create_index(op.f('ix_soundings_attachment_id'), 'soundings', ['attachment_id'], unique=False)
    op.create_foreign_key(
        'fk_soundings_attachment_id_attachments',
        'soundings',
        'attachments',
        ['attachment_id'],
        ['id'],
    )
    op.drop_column('soundings', 'reading')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soundings', sa.Column('reading', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False))
    op.drop_constraint(
        'fk_soundings_attachment_id_attachments',
        'soundings',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_soundings_attachment_id'), table_name='soundings')
    op.create_unique_constraint(op.f('uq_sounding_vessel_report_date'), 'soundings', ['vessel_id', 'report_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('soundings', 'attachment_id')
    op.drop_index(op.f('ix_attachments_uploaded_by_user_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
