"""add shift advancement and dredging hours

Revision ID: f58108d080f5
Revises: d7e97511581a
Create Date: 2026-09-10 17:45:53.626088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58108d080f5'
down_revision: Union[str, Sequence[str], None] = 'd7e97511581a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('advancement_m', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('shifts', sa.Column('dredging_hours', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'dredging_hours')
    op.drop_column('shifts', 'advancement_m')
    # ### end Alembic commands ###
